# Test values to limit the load during CI
alertmanager:
  persistentVolume:
    enabled: false

compactor:
  persistentVolume:
    enabled: false

ingester:
  persistentVolume:
    enabled: false

storeGateway:
  persistentVolume:
    enabled: false
