apiVersion: v1
kind: Service
metadata:
  name: {{ template "enterprise-metrics.querierFullname" . }}
  labels:
    {{- include "enterprise-metrics.querierLabels" . | nindent 4 }}
    {{- with .Values.querier.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.querier.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "enterprise-metrics.querierSelectorLabels" . | nindent 4 }}
