apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: enterprise-metrics-admin-api
    app.kubernetes.io/managed-by: Helmraiser
    chart: enterprise-metrics-1.5.4
    heritage: Helm
    release: enterprise-metrics
  name: enterprise-metrics-admin-api
  namespace: enterprise-metrics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: enterprise-metrics-admin-api
      release: enterprise-metrics
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: dcd1d2d2eb8582155a10a02bd431b2c8762d76d73c9ea4ba4db9ce459135cea9
      labels:
        app: enterprise-metrics-admin-api
        gossip_ring_member: "true"
        name: admin-api
        release: enterprise-metrics
        target: admin-api
    spec:
      affinity: {}
      containers:
      - args:
        - -target=admin-api
        - -config.file=/etc/enterprise-metrics/enterprise-metrics.yaml
        - -memberlist.join=enterprise-metrics-gossip-ring
        env: null
        image: grafana/metrics-enterprise:v1.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe: null
        name: enterprise-metrics
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        - containerPort: 9095
          name: grpc
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/enterprise-metrics
          name: config
        - mountPath: /var/enterprise-metrics
          name: runtime-config
        - mountPath: /license
          name: license
        - mountPath: /data
          name: storage
          subPath: null
      initContainers: null
      nodeSelector: {}
      securityContext: {}
      serviceAccountName: enterprise-metrics
      terminationGracePeriodSeconds: 60
      tolerations: []
      volumes:
      - name: config
        secret:
          secretName: enterprise-metrics
      - configMap:
          name: enterprise-metrics-runtime
        name: runtime-config
      - name: license
        secret:
          secretName: enterprise-metrics-license
      - emptyDir: {}
        name: storage
