apiVersion: v1
kind: Service
metadata:
  name: {{ template "enterprise-metrics.ingesterFullname" . }}
  labels:
    {{- include "enterprise-metrics.ingesterLabels" . | nindent 4 }}
    {{- with .Values.ingester.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.ingester.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "enterprise-metrics.ingesterSelectorLabels" . | nindent 4 }}
