{{- if not .Values.useExternalLicense -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.secretName }}
  labels:
    {{- include "enterprise-metrics.labels" . | nindent 4 }}
data:
  license.jwt: {{ .Values.license.contents | b64enc }}
{{- end }}
